# model path: model_root_dir/model_name
# tensorboard path: log_root_dir/model_name
model_root_dir: saved_models            # root path for savinng models
log_root_dir: logs                      # root path for tensorboard logs
model_name: baseline
metatrain_folder: ../../dataset/miniimagenet/train
metaval_folder: ../../dataset/miniimagenet/test

num_tasks_per_batch: 4
num_classes_per_task: 5             # n in n-way learning
num_outer_samples_per_class: 5      # number of samples per class for outer loop learning
num_inner_sample_per_class: 1       # i.e., k in k-shot learning

network:
    num_channels: 32
    norm: batch_norm
    max_pool: True
    second_derivatives: True
    inner_learning_rate: 1e-3 # inner loop learning rate
    num_inner_updates: 1
    learning_rate: 1e-2   # outer loop learning rate